
[build.environment]
  NODE_VERSION = "16"

[build]
  command = "pnpm run build && pnpm run example:build"
  publish = "example/netlify"
  functions = "example/netlify/functions"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
